<?php
/* 6/21/2021
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

$f[0] = 0;
$f[1] = 1;

$sum = 0;
$i = 2;
do {
    $f[$i] = $f[$i-2] + $f[$i-1];

    if ($f[$i] >= 4000000) break;

    if ($f[$i] % 2 == 0) {
        $sum += $f[$i];
    }

    $i++;
} while (true);

echo $sum;
